name: git
version: 2.2.1
description: >-
  Git command line wrapper. Exposes a Git directory abstraction that makes it
  easy to inspect and manipulate a local Git repository.
repository: https://github.com/kevmoo/git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.0.0

dev_dependencies:
  test: ^1.6.0
  test_descriptor: ^2.0.0
  very_good_analysis: ^5.1.0
